### ISSUE TITLE
루트 모듈을 제외한 다른 모듈은 BrowserModule을 임포트하는 것이 아니라 CommonModule을 임포트합니다

### ISSUE THREAD

**Issue by ungmo2** [Esdyee/Namu-Project#21]
https://github.com/Esdyee/Namu-Project/blob/f996ba72c81d7cbe6776310e8695b2ccb2d29f89/Namu-Project/src/app/login/login.module.ts#L1

**Comment by Esdyee** [comment]
해당 부분은 수정 완료 했습니다. 감사합니다.
