### ISSUE TITLE
폴더 구조

### ISSUE THREAD

**Issue by ungmo2** [Esdyee/Namu-Project#22]
폴더 구조가 일반적이지 않네요. Angular CLI가 생성해 주는 폴더 구조로 하지 않은 이유가 있나요??

**Comment by Esdyee** [comment]
초기에는 github를 말그대로 개인 파일 push하고 pull하는 정도만 알았기에
폴더 구조를 변경하여 static 버전과 dev 버전을 구분하였습니다.
금주 내로 1차로 static한 버전을 github pages에 업로드할 계획이 있습니다.
